In [ ]:
import pandas as pd

df_orders = pd.read_csv('data/olist_orders_dataset.csv')
df_orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [ ]:
df_orders.shape

(99441, 8)

In [ ]:
df_orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='object')

In [ ]:
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [ ]:
df_orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [ ]:
# CONVERSAO DAS COLUNAS DE DATA PARA DATETIME
colunas_data = [
    'order_purchase_timestamp',
    'order_approved_at',
    'order_delivered_carrier_date',
    'order_delivered_customer_date',
    'order_estimated_delivery_date'
]

for coluna in colunas_data:
    df_orders[coluna] = pd.to_datetime(df_orders[coluna])
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: datetime64[ns](5), object(3)
memory usage: 6.1+ MB

In [ ]:
## CALCULO DO TEMPO DE ENTREGA EM DIAS
df_orders['tempo_entrega_dias'] = (
    df_orders['order_delivered_customer_date'] 
    - df_orders['order_purchase_timestamp']
    ).dt.days

df_orders[['order_purchase_timestamp', 
           'order_delivered_customer_date', 
           'tempo_entrega_dias']]

,order_purchase_timestamp,order_delivered_customer_date,tempo_entrega_dias
0,2017-10-02 10:56:33,2017-10-10 21:25:13,8.0
1,2018-07-24 20:41:37,2018-08-07 15:27:45,13.0
2,2018-08-08 08:38:49,2018-08-17 18:06:29,9.0
3,2017-11-18 19:28:06,2017-12-02 00:28:42,13.0
4,2018-02-13 21:18:39,2018-02-16 18:17:02,2.0
...,...,...,...
99436,2017-03-09 09:54:05,2017-03-17 15:08:01,8.0
99437,2018-02-06 12:58:58,2018-02-28 17:37:56,22.0
99438,2017-08-27 14:46:43,2017-09-21 11:24:17,24.0
99439,2018-01-08 21:28:27,2018-01-25 23:32:54,17.0
99440,2018-03-08 20:57:30,2018-03-16 13:08:30,7.0

In [ ]:
# CONVERTENDO A COLUNA PARA INT64
df_orders['tempo_entrega_dias'] =(
    df_orders['tempo_entrega_dias']
    .astype('Int64')
    )
df_orders[['tempo_entrega_dias']]

       tempo_entrega_dias
0                       8
1                      13
2                       9
3                      13
4                       2
...                   ...
99436                   8
99437                  22
99438                  24
99439                  17
99440                   7

[99441 rows x 1 columns]

In [ ]:
df_orders['tempo_entrega_dias'].describe()

count      96476.0
mean     12.094086
std       9.551746
min            0.0
25%            6.0
50%           10.0
75%           15.0
max          209.0
Name: tempo_entrega_dias, dtype: Float64

In [ ]:
#PEDIDOS SEM ENTREGA
df_orders[
    df_orders['tempo_entrega_dias'].isnull()
]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,tempo_entrega_dias
6,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,NaT,NaT,2017-05-09,<NA>
44,ee64d42b8cf066f35eac1cf57de1aa85,caded193e8e47b8362864762a83db3c5,shipped,2018-06-04 16:44:48,2018-06-05 04:31:18,2018-06-05 14:32:00,NaT,2018-06-28,<NA>
103,0760a852e4e9d89eb77bf631eaaf1c84,d2a79636084590b7465af8ab374a8cf5,invoiced,2018-08-03 17:44:42,2018-08-07 06:15:14,NaT,NaT,2018-08-21,<NA>
128,15bed8e2fec7fdbadb186b57c46c92f2,f3f0e613e0bdb9c7cee75504f0f90679,processing,2017-09-03 14:22:03,2017-09-03 14:30:09,NaT,NaT,2017-10-03,<NA>
154,6942b8da583c2f9957e990d028607019,52006a9383bf149a4fb24226b173106f,shipped,2018-01-10 11:33:07,2018-01-11 02:32:30,2018-01-11 19:39:23,NaT,2018-02-07,<NA>
...,...,...,...,...,...,...,...,...,...
99283,3a3cddda5a7c27851bd96c3313412840,0b0d6095c5555fe083844281f6b093bb,canceled,2018-08-31 16:13:44,NaT,NaT,NaT,2018-10-01,<NA>
99313,e9e64a17afa9653aacf2616d94c005b8,b4cd0522e632e481f8eaf766a2646e86,processing,2018-01-05 23:07:24,2018-01-09 07:18:05,NaT,NaT,2018-02-06,<NA>
99347,a89abace0dcc01eeb267a9660b5ac126,2f0524a7b1b3845a1a57fcf3910c4333,canceled,2018-09-06 18:45:47,NaT,NaT,NaT,2018-09-27,<NA>
99348,a69ba794cc7deb415c3e15a0a3877e69,726f0894b5becdf952ea537d5266e543,unavailable,2017-08-23 16:28:04,2017-08-28 15:44:47,NaT,NaT,2017-09-15,<NA>
99415,5fabc81b6322c8443648e1b21a6fef21,32c9df889d41b0ee8309a5efb6855dcb,unavailable,2017-10-10 10:50:03,2017-10-14 18:35:57,NaT,NaT,2017-10-23,<NA>

In [ ]:
# PEDIDOS COM TEMPO DE ENTREGA ACIMA DE 30 DIAS
df_orders[
    df_orders['tempo_entrega_dias'] > 30
] [[
    'order_id',
    'order_purchase_timestamp',
    'tempo_entrega_dias'
]]

,order_id,order_purchase_timestamp,tempo_entrega_dias
41,6ea2f835b4556291ffdc53fa0b3b95e8,2017-11-24 21:27:48,33
97,6a0a8bfbbe700284feb0845d95e0867f,2017-11-22 11:32:22,36
110,9d531c565e28c3e0d756192f84d8731f,2017-11-28 21:00:44,56
115,8fc207e94fa91a7649c5a5dab690272a,2017-11-26 17:49:46,54
252,f31535f21d145b2345e2bf7f09d62322,2018-02-01 07:47:34,81
...,...,...,...
99121,25f6cb0e242a4c0bacc239397614422e,2017-11-20 12:50:49,32
99266,76a948cd55bf22799753720d4545dd2d,2018-01-30 02:41:30,47
99279,4cf09d9e5ebbe0f91ddd7bf9aae891cd,2018-07-19 08:37:26,32
99423,38e9133ce29f6bbe35aed9c3863dce01,2017-10-12 20:54:11,39
99432,cfa78b997e329a5295b4ee6972c02979,2017-12-20 09:52:41,37

In [ ]:
# MÉDIA DE TEMPO DE ENTREGA
media_entrega = df_orders['tempo_entrega_dias'].mean()
round(media_entrega, 2)

np.float64(12.09)

In [ ]:
#IDENTIFICANDO PEDIDOS ATRASADOS
df_orders ['pedido_atrasado'] = (
    df_orders['order_delivered_customer_date'] 
    > df_orders['order_estimated_delivery_date']
)
# SUBSTITUINDO TRUE/FALSE POR TEXTOS MAIS VISUAIS
df_orders['pedido_atrasado'] = (
    df_orders['pedido_atrasado']
    .map ({True: 'Atrasou',
            False: 'Chegou no prazo'})

)

df_orders[[
    'order_delivered_customer_date',
    'order_estimated_delivery_date',
    'pedido_atrasado'
]]

,order_delivered_customer_date,order_estimated_delivery_date,pedido_atrasado
0,2017-10-10 21:25:13,2017-10-18,Chegou no prazo
1,2018-08-07 15:27:45,2018-08-13,Chegou no prazo
2,2018-08-17 18:06:29,2018-09-04,Chegou no prazo
3,2017-12-02 00:28:42,2017-12-15,Chegou no prazo
4,2018-02-16 18:17:02,2018-02-26,Chegou no prazo
...,...,...,...
99436,2017-03-17 15:08:01,2017-03-28,Chegou no prazo
99437,2018-02-28 17:37:56,2018-03-02,Chegou no prazo
99438,2017-09-21 11:24:17,2017-09-27,Chegou no prazo
99439,2018-01-25 23:32:54,2018-02-15,Chegou no prazo
99440,2018-03-16 13:08:30,2018-04-03,Chegou no prazo

In [ ]:
df_orders['pedido_atrasado'].value_counts()

pedido_atrasado
Chegou no prazo    91614
Atrasou             7827
Name: count, dtype: int64

In [ ]:
# PORCENTAGEM DE PEDIDOS ATRASADOS
percentual_atraso = (
    df_orders['pedido_atrasado'].value_counts(normalize=True) * 100
)

round(percentual_atraso, 2)

pedido_atrasado
Chegou no prazo    92.13
Atrasou             7.87
Name: proportion, dtype: float64

In [ ]:
#QUANTIDADE DE PEDIDOS POR STATUS
df_orders.groupby('order_status').size().sort_values(ascending=False)

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
dtype: int64

In [ ]:
df_orders['mes_compra'] = (
    df_orders['order_purchase_timestamp']
    .dt.month
)
df_orders[['order_purchase_timestamp', 'mes_compra']]

      order_purchase_timestamp  mes_compra
0          2017-10-02 10:56:33          10
1          2018-07-24 20:41:37           7
2          2018-08-08 08:38:49           8
3          2017-11-18 19:28:06          11
4          2018-02-13 21:18:39           2
...                        ...         ...
99436      2017-03-09 09:54:05           3
99437      2018-02-06 12:58:58           2
99438      2017-08-27 14:46:43           8
99439      2018-01-08 21:28:27           1
99440      2018-03-08 20:57:30           3

[99441 rows x 2 columns]

In [ ]:
mes = {
    1: 'Janeiro',
    2: 'Fevereiro',
    3: 'Março',
    4: 'Abril',
    5: 'Maio',
    6: 'Junho',
    7: 'Julho',
    8: 'Agosto',
    9: 'Setembro',
    10: 'Outubro',
    11: 'Novembro',
    12: 'Dezembro'
}
df_orders['nome_mes_compra'] = (
    df_orders['mes_compra']
    .map(mes)
)
df_orders[['mes_compra', 'nome_mes_compra']]

       mes_compra nome_mes_compra
0              10         Outubro
1               7           Julho
2               8          Agosto
3              11        Novembro
4               2       Fevereiro
...           ...             ...
99436           3           Março
99437           2       Fevereiro
99438           8          Agosto
99439           1         Janeiro
99440           3           Março

[99441 rows x 2 columns]

In [ ]:
## QUANTIDADE DE PEDIDOS POR MÊS
pedidos_por_mes = (df_orders
.groupby('nome_mes_compra')
.size()
.sort_values(ascending=False)
)

pedidos_por_mes

nome_mes_compra
Agosto       10843
Maio         10573
Julho        10318
Março         9893
Junho         9412
Abril         9343
Fevereiro     8508
Janeiro       8069
Novembro      7544
Dezembro      5674
Outubro       4959
Setembro      4305
dtype: int64

In [ ]:
## ORGANIZANDO OS MESES EM ORDEM CRONOLÓGICA
ordem_mes = [
    'Janeiro',
    'Fevereiro',
    'Março',
    'Abril',
    'Maio',
    'Junho',
    'Julho',
    'Agosto',
    'Setembro',
    'Outubro',
    'Novembro',
    'Dezembro'
]
pedidos_por_mes = (
    df_orders['nome_mes_compra']
    .value_counts()
    .reindex(ordem_mes)
)

pedidos_por_mes

nome_mes_compra
Janeiro       8069
Fevereiro     8508
Março         9893
Abril         9343
Maio         10573
Junho         9412
Julho        10318
Agosto       10843
Setembro      4305
Outubro       4959
Novembro      7544
Dezembro      5674
Name: count, dtype: int64

In [ ]:
# LEITURA DO DATASET DE CLIENTES
df_customers = pd.read_csv('data/olist_customers_dataset.csv')
df_customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [ ]:
df_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [ ]:
# JOIN ENTRE PEDIDOS E CLIENTES
df_orders_customers = pd.merge(
    df_orders,
    df_customers,
    on='customer_id',
    how='inner'
)
df_orders_customers.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,tempo_entrega_dias,pedido_atrasado,mes_compra,nome_mes_compra,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,8,Chegou no prazo,10,Outubro,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,13,Chegou no prazo,7,Julho,af07308b275d755c9edb36a90c618231,47813,barreiras,BA
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,9,Chegou no prazo,8,Agosto,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,13,Chegou no prazo,11,Novembro,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,2,Chegou no prazo,2,Fevereiro,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP

In [ ]:
# REMOVENDO COLUNA REDUNDANTE
df_orders_customers = (
    df_orders_customers
    .drop(columns=['tempo_entrega', 'mes_compra'])
)
df_orders_customers.head()

KeyError: "['tempo_entrega'] not found in axis"

In [ ]:
# REMOVENDO COLUNA REDUNDANTE
df_orders_customers = (
    df_orders_customers
    .drop(columns=['mes_compra'])
)
df_orders_customers.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,tempo_entrega_dias,pedido_atrasado,nome_mes_compra,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,8,Chegou no prazo,Outubro,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,13,Chegou no prazo,Julho,af07308b275d755c9edb36a90c618231,47813,barreiras,BA
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,9,Chegou no prazo,Agosto,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,13,Chegou no prazo,Novembro,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,2,Chegou no prazo,Fevereiro,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP

In [ ]:
## QUANTIDADE DE PEDIDOS POR ESTADO
pedidos_por_estado = (
    df_orders_customers
    .groupby('customer_state')
    .size()
    .sort_values(ascending=False)
)

pedidos_por_estado

customer_state
SP    41746
RJ    12852
MG    11635
RS     5466
PR     5045
SC     3637
BA     3380
DF     2140
ES     2033
GO     2020
PE     1652
CE     1336
PA      975
MT      907
MA      747
MS      715
PB      536
PI      495
RN      485
AL      413
SE      350
TO      280
RO      253
AM      148
AC       81
AP       68
RR       46
dtype: int64

In [ ]:
media_entrega_por_estado = (
    df_orders_customers
    .groupby('customer_state')['tempo_entrega_dias']
    .mean()
    .sort_values(ascending=False)
)
media_entrega_por_estado

customer_state
RR     28.97561
AP    26.731343
AM    25.986207
AL    24.040302
PA    23.316068
MA    21.117155
SE    21.029851
CE    20.817826
AC      20.6375
PB    19.953578
PI    18.993697
RO     18.91358
BA      18.8664
RN    18.824895
PE    17.965474
MT    17.593679
TO    17.226277
ES     15.33183
MS    15.191155
GO    15.150741
RJ    14.849186
RS    14.819237
SC     14.47956
DF    12.509135
MG    11.543813
PR    11.526711
SP     8.298061
Name: tempo_entrega_dias, dtype: Float64

In [ ]:
media_entrega_por_estado = (
    df_orders_customers
    .groupby('customer_state')['tempo_entrega_dias']
    .mean()
    .sort_values(ascending=False)
)
round(media_entrega_por_estado, 2)

customer_state
RR    28.98
AP    26.73
AM    25.99
AL    24.04
PA    23.32
MA    21.12
SE    21.03
CE    20.82
AC    20.64
PB    19.95
PI    18.99
RO    18.91
BA    18.87
RN    18.82
PE    17.97
MT    17.59
TO    17.23
ES    15.33
MS    15.19
GO    15.15
RJ    14.85
RS    14.82
SC    14.48
DF    12.51
MG    11.54
PR    11.53
SP      8.3
Name: tempo_entrega_dias, dtype: Float64

In [ ]:
top_cidades = (
    df_orders_customers
    .groupby('customer_city')
    .size()
    .sort_values(ascending=False)
    .head(10)
)
top_cidades

customer_city
sao paulo                15540
rio de janeiro            6882
belo horizonte            2773
brasilia                  2131
curitiba                  1521
campinas                  1444
porto alegre              1379
salvador                  1245
guarulhos                 1189
sao bernardo do campo      938
dtype: int64

In [ ]:
atraso_por_estado = (
    df_orders_customers[
        df_orders_customers['pedido_atrasado'] == 'Atrasou'
    ]
    .groupby('customer_state')
    .size()
    .sort_values(ascending=False)
)

atraso_por_estado

customer_state
SP    2387
RJ    1664
MG     638
BA     457
RS     382
SC     346
PR     246
ES     244
CE     196
PE     172
GO     160
DF     147
MA     141
PA     117
AL      95
MS      81
PI      76
MT      60
PB      57
SE      51
RN      51
TO      35
RO       7
AM       6
RR       5
AP       3
AC       3
dtype: int64

In [ ]:
total_pedidos_estado = (
    df_orders_customers
    .groupby('customer_state')
    .size()
)

pedidos_atrasados_estado = (
    df_orders_customers[
        df_orders_customers['pedido_atrasado'] == 'Atrasou'
    ]
    .groupby('customer_state')
    .size()
)

taxa_atraso_estado = (
    (pedidos_atrasados_estado / total_pedidos_estado) * 100
)

round(taxa_atraso_estado.sort_values(ascending=False), 2)

customer_state
AL    23.00
MA    18.88
PI    15.35
CE    14.67
SE    14.57
BA    13.52
RJ    12.95
TO    12.50
ES    12.00
PA    12.00
MS    11.33
RR    10.87
PB    10.63
RN    10.52
PE    10.41
SC     9.51
GO     7.92
RS     6.99
DF     6.87
MT     6.62
SP     5.72
MG     5.48
PR     4.88
AP     4.41
AM     4.05
AC     3.70
RO     2.77
dtype: float64

In [ ]:
df_final = df_orders_customers[[
    'order_id',
    'customer_id',
    'customer_city',
    'customer_state',
    'order_status',
    'order_purchase_timestamp',
    'order_delivered_customer_date',
    'order_estimated_delivery_date',
    'tempo_entrega_dias',
    'pedido_atrasado',
    'nome_mes_compra'
]]

df_final.head()

,order_id,customer_id,customer_city,customer_state,order_status,order_purchase_timestamp,order_delivered_customer_date,order_estimated_delivery_date,tempo_entrega_dias,pedido_atrasado,nome_mes_compra
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,sao paulo,SP,delivered,2017-10-02 10:56:33,2017-10-10 21:25:13,2017-10-18,8,Chegou no prazo,Outubro
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,barreiras,BA,delivered,2018-07-24 20:41:37,2018-08-07 15:27:45,2018-08-13,13,Chegou no prazo,Julho
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,vianopolis,GO,delivered,2018-08-08 08:38:49,2018-08-17 18:06:29,2018-09-04,9,Chegou no prazo,Agosto
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,sao goncalo do amarante,RN,delivered,2017-11-18 19:28:06,2017-12-02 00:28:42,2017-12-15,13,Chegou no prazo,Novembro
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,santo andre,SP,delivered,2018-02-13 21:18:39,2018-02-16 18:17:02,2018-02-26,2,Chegou no prazo,Fevereiro

In [ ]:
# EXPORTANDO DATASET FINAL TRATADO
df_final.to_csv('DataSet_Final/df_final.csv', index=False)